version: "2.3"
services:
  web:
    image: shop-item
    container_name: shop_api
    ports:
      - 9080:9080
    depends_on:
      - mysql
    volumes:
      - ./config.json:/app/config.json
  mysql:
    image: mysql:5.7 
    container_name: shop_mysql
    command: mysqld --user=root
    volumes:
      - ./shop.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=shop
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root

